baseurl = "https://gupta-anukriti.com/"
languageCode = "en-us"
title = "ANUKRITI GUPTA"
theme = "hyde-hyde"
googleAnalytics = ""
disqusShortname = "Anukriti - portfolio"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

## Site settings
[params]
    author = "ANUKRITI GUPTA"
    authorimage = "/img/pic.jpg"
    description = "Data Scientist | Mathematican | IIT Bombay"
  #  description = "\"Contact data ages like fish not wine…it gets worse as it gets older, not better.\" - Gregg Thaler"

    # options for highlight.js (version, additional languages, and theme)
    highlightjs = true
    highlightjsstyle = "github"
    math = true
    copyright = "&copy; 2018. All rights reserved."
    
## Social Accounts  
[params.social]
  	email = "gupta17anukriti@gmail.com"
  	linkedin = "anukriti-gupta"
  	github = "Anu-kriti"


[[menu.main]]
    name = "About Me"
    url = "/about/"

[[menu.main]]
    name = "Papers"
    identifier = "papers"
    weight=300
    url = "/papers/"
    
#[[menu.main]]
#    name = "Resume"
#    identifier = "resume"
#    weight=300
#    url = "/pdf/Resume_Anukriti_Gupta.pdf"

[[menu.main]]
    name = "Extra-currics"
    identifier = "Extra-currics"
    url = "/Extra-currics/"
  
  
[[menu.main]]
    name = "Achievements"
    identifier = "achievement"
    url = "/achievement/"
  
[[menu.main]]
    name = "Internships"
    identifier = "Internship"
    url = "/internship/"

  
[[menu.main]]
    name = "Education"
    identifier = "education"
    url = "/education/"
  

  