
baseurl = "https://gupta-anukriti.netlify.com/"
languageCode = "en"

title = "ANUKRITI GUPTA"
theme = "hyde-hyde"

#googleAnalytics = ""
disqusShortname = "Anukriti-portfolio"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeURLs = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

## Site settings
[params]
    author = "ANUKRITI GUPTA"
    #themeColor = "theme-base-0c"
    authorimage = "/img/pic.png"
    dateformat = "Jan 2, 2006"
    description = "Data Scientist | Mathematican |   IIT Bombay"
  #  description = "\"Contact data ages like fish not wine…it gets worse as it gets older, not better.\" - Gregg Thaler"

    # options for highlight.js (version, additional languages, and theme)
    highlightjs = true
    highlightjsstyle = "github"
    math = true
    copyright = "&copy;. All rights reserved."
    
## Social Accounts  
[params.social]
  	email = "gupta17anukriti@gmail.com"
  	linkedin = "anukriti-gupta-5a583921"
  	github = "Anu-kriti"


[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 10
    url = "/about/"

[[menu.main]]
    name = "Education"
    identifier = "education"
    weight = 20
    url = "/education/"

[[menu.main]]
    name = "Internships"
    identifier = "Internship"
    weight = 30
    url = "/internship/"  
 
[[menu.main]]
    name = "Achievements"
    identifier = "achievement"
    weight = 40
    url = "/achievement/"

[[menu.main]]
    name = "Papers"
    identifier = "papers"
    weight=100
    url = "/papers/"
    
[[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight=300
    url = "/pdf/Resume_Anukriti_Gupta.pdf"

[[menu.main]]
    name = "Extra-currics"
    identifier = "Extra-currics"
    weight = 50
    url = "/Extra-currics/"

  

  


  